In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("transactions.csv")

In [4]:
print("shape:", df.shape)

shape: (12, 6)

In [5]:
df

      id   amount    type country customer_id    status
0   T001   1000.0  credit      US        C001  approved
1   T002    200.0   debit      UK        C002  approved
2   T003    500.0   debit      US        C001  approved
3   T004    750.0  credit      IN        C003  approved
4   T005    150.0   debit      US        C002  approved
5   T006   9000.0  credit      IN        C004  approved
6   T007    300.0   debit      UK        C003  approved
7   T008   1200.0  credit      US        C004  approved
8   T009      NaN   debit      US        C001  approved
9   T010    500.0  credit     NaN        C002   pending
10  T011    850.0   debit      UK        C001  declined
11  T012  15000.0  credit      US         NaN  approved

In [6]:
df.describe()

             amount
count     11.000000
mean    2677.272727
std     4811.775329
min      150.000000
25%      400.000000
50%      750.000000
75%     1100.000000
max    15000.000000

In [7]:
df.isnull()

       id  amount   type  country  customer_id  status
0   False   False  False    False        False   False
1   False   False  False    False        False   False
2   False   False  False    False        False   False
3   False   False  False    False        False   False
4   False   False  False    False        False   False
5   False   False  False    False        False   False
6   False   False  False    False        False   False
7   False   False  False    False        False   False
8   False    True  False    False        False   False
9   False   False  False     True        False   False
10  False   False  False    False        False   False
11  False   False  False    False         True   False

In [9]:
df.isnull().sum()

id             0
amount         1
type           0
country        1
customer_id    1
status         0
dtype: int64

In [10]:
df[df.isnull().any(axis=1)]

      id   amount    type country customer_id    status
8   T009      NaN   debit      US        C001  approved
9   T010    500.0  credit     NaN        C002   pending
11  T012  15000.0  credit      US         NaN  approved

In [11]:
df["amount"] = df["amount"].fillna(df["amount"].mean())

In [12]:
df["country"] = df["country"].fillna("Unknown")

In [13]:
df = df.dropna(subset=["customer_id"])

In [14]:
df.isnull().sum()

id             0
amount         0
type           0
country        0
customer_id    0
status         0
dtype: int64

In [15]:
import numpy as np

In [17]:
df["risk_score"] = np.where(df["amount"] > 5000, "high",
                            np.where(df["amount"] > 1000, "medium", "low"))

In [18]:
df

      id       amount    type  country customer_id    status risk_score
0   T001  1000.000000  credit       US        C001  approved        low
1   T002   200.000000   debit       UK        C002  approved        low
2   T003   500.000000   debit       US        C001  approved        low
3   T004   750.000000  credit       IN        C003  approved        low
4   T005   150.000000   debit       US        C002  approved        low
5   T006  9000.000000  credit       IN        C004  approved       high
6   T007   300.000000   debit       UK        C003  approved        low
7   T008  1200.000000  credit       US        C004  approved     medium
8   T009  2677.272727   debit       US        C001  approved     medium
9   T010   500.000000  credit  Unknown        C002   pending        low
10  T011   850.000000   debit       UK        C001  declined        low

In [24]:
risk_score_count = df["risk_score"].value_counts()

In [25]:
risk_score_count

risk_score
low       8
medium    2
high      1
Name: count, dtype: int64

In [28]:
print(df.groupby("country")["amount"].mean())

country
IN         4875.000000
UK          450.000000
US         1105.454545
Unknown     500.000000
Name: amount, dtype: float64

In [29]:
df.to_csv("cleaned_transactions.csv", index=False)
print("File saved successfully")

File saved successfully